"""add storyboard phase A planning domain

Revision ID: d9e8c7b6a5f4
Revises: c4f8d3f2e1a9
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "d9e8c7b6a5f4"
down_revision = "c4f8d3f2e1a9"
branch_labels = None
depends_on = None


def _uuid():
    return postgresql.UUID(as_uuid=True).with_variant(sa.String(36), "sqlite")


def _json():
    return sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def _timestamps():
    return [sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False)]


def upgrade() -> None:
    op.create_table("stories", sa.Column("id", _uuid(), primary_key=True), sa.Column("project_id", _uuid(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.Text(), nullable=False), sa.Column("base_story", sa.Text(), nullable=False), sa.Column("logline", sa.Text()), sa.Column("synopsis", sa.Text()), sa.Column("target_duration_sec", sa.Numeric(), nullable=False), sa.Column("audience", sa.Text()), sa.Column("tone", sa.Text()), sa.Column("genre", sa.Text()), sa.Column("visual_style", sa.Text()), sa.Column("point_of_view", sa.Text()), sa.Column("production_notes", sa.Text()), sa.Column("approval_state", sa.String(32), nullable=False, server_default="draft"), sa.Column("active_storyboard_version_id", _uuid()), sa.Column("default_provider_profile_id", _uuid()), *_timestamps())
    op.create_index("ix_stories_project_id", "stories", ["project_id"])
    op.create_table("planning_media_assets", sa.Column("id", _uuid(), primary_key=True), sa.Column("project_id", _uuid(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("kind", sa.String(48), nullable=False), sa.Column("source_type", sa.String(48), nullable=False), sa.Column("managed_uri", sa.Text(), nullable=False), sa.Column("sha256", sa.String(64)), sa.Column("mime_type", sa.String(128)), sa.Column("width", sa.Integer()), sa.Column("height", sa.Integer()), sa.Column("duration_sec", sa.Numeric()), sa.Column("approval_state", sa.String(32), nullable=False, server_default="draft"), sa.Column("metadata_json", _json(), nullable=False, server_default=sa.text("'{}'")), *_timestamps())
    op.create_index("ix_planning_media_assets_project_id", "planning_media_assets", ["project_id"])
    op.create_table("characters", sa.Column("id", _uuid(), primary_key=True), sa.Column("story_id", _uuid(), sa.ForeignKey("stories.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.Text(), nullable=False), sa.Column("role", sa.Text()), sa.Column("age_range", sa.Text()), sa.Column("physical_description", sa.Text()), sa.Column("personality", sa.Text()), sa.Column("speaking_style", sa.Text()), sa.Column("wardrobe", sa.Text()), sa.Column("consistency_prompt", sa.Text()), sa.Column("negative_identity_prompt", sa.Text()), sa.Column("identity_method", sa.String(64)), sa.Column("approval_state", sa.String(32), nullable=False, server_default="draft"), sa.Column("assigned_voice_profile_id", _uuid()), *_timestamps())
    op.create_index("ix_characters_story_id", "characters", ["story_id"])
    op.create_table("voice_profiles", sa.Column("id", _uuid(), primary_key=True), sa.Column("story_id", _uuid(), sa.ForeignKey("stories.id", ondelete="CASCADE"), nullable=False), sa.Column("character_id", _uuid(), sa.ForeignKey("characters.id", ondelete="SET NULL")), sa.Column("name", sa.Text(), nullable=False), sa.Column("source_type", sa.String(48), nullable=False), sa.Column("provider", sa.String(80)), sa.Column("provider_voice_reference", sa.Text()), sa.Column("language", sa.String(32)), sa.Column("accent", sa.Text()), sa.Column("presentation", sa.Text()), sa.Column("tone", sa.Text()), sa.Column("speaking_directions", sa.Text()), sa.Column("pacing", sa.Text()), sa.Column("energy", sa.Text()), sa.Column("pronunciation_notes", sa.Text()), sa.Column("source_asset_id", _uuid(), sa.ForeignKey("planning_media_assets.id", ondelete="SET NULL")), sa.Column("source_description", sa.Text()), sa.Column("consent_required", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("consent_confirmed", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("consent_notes", sa.Text()), sa.Column("usage_notes", sa.Text()), sa.Column("approval_state", sa.String(32), nullable=False, server_default="draft"), *_timestamps())
    op.create_index("ix_voice_profiles_story_id", "voice_profiles", ["story_id"])
    op.create_table("character_reference_assets", sa.Column("id", _uuid(), primary_key=True), sa.Column("character_id", _uuid(), sa.ForeignKey("characters.id", ondelete="CASCADE"), nullable=False), sa.Column("asset_id", _uuid(), sa.ForeignKey("planning_media_assets.id", ondelete="CASCADE"), nullable=False), sa.Column("reference_role", sa.String(32), nullable=False), sa.Column("approved", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("order_index", sa.Integer(), nullable=False, server_default="0"), *_timestamps(), sa.UniqueConstraint("character_id", "order_index", name="uq_character_reference_order"))
    op.create_index("ix_character_reference_assets_character_id", "character_reference_assets", ["character_id"])
    op.create_table("chapters", sa.Column("id", _uuid(), primary_key=True), sa.Column("story_id", _uuid(), sa.ForeignKey("stories.id", ondelete="CASCADE"), nullable=False), sa.Column("order_index", sa.Integer(), nullable=False), sa.Column("title", sa.Text(), nullable=False), sa.Column("summary", sa.Text()), sa.Column("approval_state", sa.String(32), nullable=False, server_default="draft"), sa.Column("archived_at", sa.DateTime(timezone=True)), *_timestamps(), sa.UniqueConstraint("story_id", "order_index", name="uq_chapter_story_order"))
    op.create_index("ix_chapters_story_id", "chapters", ["story_id"])
    op.create_table("scenes", sa.Column("id", _uuid(), primary_key=True), sa.Column("chapter_id", _uuid(), sa.ForeignKey("chapters.id", ondelete="CASCADE"), nullable=False), sa.Column("order_index", sa.Integer(), nullable=False), sa.Column("title", sa.Text(), nullable=False), sa.Column("summary", sa.Text()), sa.Column("narrative_purpose", sa.Text()), sa.Column("location", sa.Text()), sa.Column("conflict_or_beat", sa.Text()), sa.Column("approval_state", sa.String(32), nullable=False, server_default="draft"), sa.Column("archived_at", sa.DateTime(timezone=True)), *_timestamps(), sa.UniqueConstraint("chapter_id", "order_index", name="uq_scene_chapter_order"))
    op.create_index("ix_scenes_chapter_id", "scenes", ["chapter_id"])
    op.create_table("shots", sa.Column("id", _uuid(), primary_key=True), sa.Column("scene_id", _uuid(), sa.ForeignKey("scenes.id", ondelete="CASCADE"), nullable=False), sa.Column("order_index", sa.Integer(), nullable=False), sa.Column("title", sa.Text(), nullable=False), sa.Column("duration_sec", sa.Numeric(), nullable=False), sa.Column("duration_override_reason", sa.Text()), sa.Column("story_purpose", sa.Text()), sa.Column("visual_description", sa.Text()), sa.Column("location", sa.Text()), sa.Column("continuity_source_type", sa.String(48), nullable=False, server_default="none"), sa.Column("continuity_source_shot_id", _uuid(), sa.ForeignKey("shots.id", ondelete="SET NULL")), sa.Column("starting_image_required", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("starting_image_asset_id", _uuid(), sa.ForeignKey("planning_media_assets.id", ondelete="SET NULL")), sa.Column("approval_state", sa.String(32), nullable=False, server_default="draft"), sa.Column("production_status", sa.String(32), nullable=False, server_default="planned"), sa.Column("blocked_reason", sa.Text()), *_timestamps(), sa.UniqueConstraint("scene_id", "order_index", name="uq_shot_scene_order"), sa.CheckConstraint("duration_sec > 0", name="ck_shot_positive_duration"))
    op.create_index("ix_shots_scene_id", "shots", ["scene_id"])
    op.create_table("shot_characters", sa.Column("shot_id", _uuid(), sa.ForeignKey("shots.id", ondelete="CASCADE"), primary_key=True), sa.Column("character_id", _uuid(), sa.ForeignKey("characters.id", ondelete="CASCADE"), primary_key=True), sa.Column("role_in_shot", sa.Text()), sa.Column("order_index", sa.Integer(), nullable=False, server_default="0"), sa.Column("continuity_notes", sa.Text()))
    op.create_table("shot_narrations", sa.Column("id", _uuid(), primary_key=True), sa.Column("shot_id", _uuid(), sa.ForeignKey("shots.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("voice_profile_id", _uuid(), sa.ForeignKey("voice_profiles.id", ondelete="SET NULL")), sa.Column("narration_text", sa.Text()), sa.Column("start_offset_sec", sa.Numeric(), nullable=False, server_default="0"), sa.Column("expected_duration_sec", sa.Numeric()), sa.Column("narration_exception_reason", sa.Text()), sa.Column("approval_state", sa.String(32), nullable=False, server_default="draft"), *_timestamps())
    op.create_table("shot_prompt_packages", sa.Column("id", _uuid(), primary_key=True), sa.Column("shot_id", _uuid(), sa.ForeignKey("shots.id", ondelete="CASCADE"), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("image_prompt", sa.Text()), sa.Column("video_prompt", sa.Text()), sa.Column("negative_prompt", sa.Text()), sa.Column("continuity_instructions", sa.Text()), sa.Column("style_lock_prompt", sa.Text()), sa.Column("provider_profile_id", _uuid()), sa.Column("provider_model_id", sa.Text()), sa.Column("proposal_id", _uuid(), sa.ForeignKey("ai_proposal_records.id", ondelete="SET NULL")), sa.Column("approval_state", sa.String(32), nullable=False, server_default="draft"), *_timestamps(), sa.UniqueConstraint("shot_id", "version", name="uq_shot_prompt_version"))
    op.create_index("ix_shot_prompt_packages_shot_id", "shot_prompt_packages", ["shot_id"])
    op.create_table("shot_model_recommendations", sa.Column("id", _uuid(), primary_key=True), sa.Column("shot_id", _uuid(), sa.ForeignKey("shots.id", ondelete="CASCADE"), nullable=False), sa.Column("recommendation_type", sa.String(24), nullable=False), sa.Column("generation_model_variant_id", _uuid(), sa.ForeignKey("model_variants.id", ondelete="SET NULL")), sa.Column("workflow_template_id", _uuid(), sa.ForeignKey("workflow_templates.id", ondelete="SET NULL")), sa.Column("rationale", sa.Text()), sa.Column("availability_status", sa.String(32), nullable=False, server_default="unknown"), sa.Column("benchmark_status", sa.String(32), nullable=False, server_default="unknown"), sa.Column("risk_status", sa.String(32)), sa.Column("acknowledged_at", sa.DateTime(timezone=True)), sa.Column("approval_state", sa.String(32), nullable=False, server_default="draft"), *_timestamps())
    op.create_index("ix_shot_model_recommendations_shot_id", "shot_model_recommendations", ["shot_id"])
    op.create_table("storyboard_versions", sa.Column("id", _uuid(), primary_key=True), sa.Column("story_id", _uuid(), sa.ForeignKey("stories.id", ondelete="CASCADE"), nullable=False), sa.Column("version_number", sa.Integer(), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="draft"), sa.Column("snapshot_json", _json(), nullable=False), sa.Column("source_proposal_id", _uuid(), sa.ForeignKey("ai_proposal_records.id", ondelete="SET NULL")), sa.Column("created_by", sa.Text()), sa.Column("approved_by", sa.Text()), sa.Column("approved_at", sa.DateTime(timezone=True)), sa.Column("superseded_at", sa.DateTime(timezone=True)), *_timestamps(), sa.UniqueConstraint("story_id", "version_number", name="uq_storyboard_version"))
    op.create_index("ix_storyboard_versions_story_id", "storyboard_versions", ["story_id"])
    op.create_table("provider_profiles", sa.Column("id", _uuid(), primary_key=True), sa.Column("provider_identifier", sa.String(32), nullable=False), sa.Column("display_name", sa.Text(), nullable=False), sa.Column("provider_model_id", sa.Text()), sa.Column("execution_mode", sa.String(32), nullable=False, server_default="disabled"), sa.Column("availability_status", sa.String(32), nullable=False, server_default="unknown"), sa.Column("privacy_classification", sa.String(64)), sa.Column("capabilities_json", _json(), nullable=False, server_default=sa.text("'{}'")), sa.Column("configuration_reference", sa.Text()), *_timestamps())
    op.create_table("task_provider_assignments", sa.Column("id", _uuid(), primary_key=True), sa.Column("story_id", _uuid(), sa.ForeignKey("stories.id", ondelete="CASCADE"), nullable=False), sa.Column("task_type", sa.String(64), nullable=False), sa.Column("provider_profile_id", _uuid(), sa.ForeignKey("provider_profiles.id", ondelete="CASCADE"), nullable=False), sa.Column("assignment_mode", sa.String(24), nullable=False, server_default="manual"), sa.Column("rationale", sa.Text()), sa.Column("priority", sa.Integer(), nullable=False, server_default="0"), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.true()), *_timestamps(), sa.UniqueConstraint("story_id", "task_type", name="uq_story_task_provider"))
    op.create_index("ix_task_provider_assignments_story_id", "task_provider_assignments", ["story_id"])
    if op.get_bind().dialect.name != "sqlite":
        op.create_foreign_key("fk_characters_assigned_voice", "characters", "voice_profiles", ["assigned_voice_profile_id"], ["id"], ondelete="SET NULL")


def downgrade() -> None:
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint("fk_characters_assigned_voice", "characters", type_="foreignkey")
    for table in ["task_provider_assignments", "provider_profiles", "storyboard_versions", "shot_model_recommendations", "shot_prompt_packages", "shot_narrations", "shot_characters", "shots", "scenes", "chapters", "character_reference_assets", "voice_profiles", "characters", "planning_media_assets", "stories"]:
        op.drop_table(table)
